# Generated by Django 4.1.3 on 2022-11-24 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_listing_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
